name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-20"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "309c9a58d5fc449e8668563d8cc2d6c1" # 替换成你实际的 KV ID

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
