name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-11-22"
keep_vars = true

[[kv_namespaces]]
binding = "domain-check_KV" 
id = "fc0876eadd4341e2b2f4f1b401fa2fdd" # 替换成你实际的 KV ID

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
